//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chap22
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyDBEntities1 : DbContext
    {
        public MyDBEntities1()
            : base("name=MyDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
    
        public virtual ObjectResult<usp_SelectMemberByUserID_Result> usp_SelectMemberByUserID(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectMemberByUserID_Result>("usp_SelectMemberByUserID", userIDParameter);
        }
    
        public virtual ObjectResult<usp_SelectMember_Result> usp_SelectMember()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectMember_Result>("usp_SelectMember");
        }
    }
}
